name: Free Threading Tests
on: [push, pull_request]
jobs:
  freethreading_tests:
    name: Free Threaded Build ${{ matrix.os.emoji }} ${{ matrix.os.name }} ${{ matrix.python }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            matrix: linux
            emoji: ğŸ§
            runs-on: [ubuntu-latest]
          - name: macOS intel
            matrix: macos
            emoji: ğŸ
            runs-on: [macos-13]
          - name: macOS silicon
            matrix: macos
            emoji: ğŸ
            runs-on: [macos-14]
          - name: Windows
            matrix: windows
            emoji: ğŸªŸ
            runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          python-version: 3.13t
          enable-cache: false
      - name: Set up Python
        run: uv python install
      - name: Install Dependencies
        run: |
          uv pip install unittest-ft
      - name: Editable build
        run: |
          uv pip install -v -e .
          python -m pip install unittest-ft
      - name: Run Tests
        run: |
          unittest-ft -r -f -s bitarray.test_bitarray
